/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/customer-materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Customer Materials */
        get: operations["list_customer_materials_api_customer_materials_get"];
        put?: never;
        /** Create Customer Material */
        post: operations["create_customer_material_api_customer_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customer-materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer Material */
        get: operations["get_customer_material_api_customer_materials__material_id__get"];
        put?: never;
        post?: never;
        /** Archive Customer Material */
        delete: operations["archive_customer_material_api_customer_materials__material_id__delete"];
        options?: never;
        head?: never;
        /** Update Customer Material */
        patch: operations["update_customer_material_api_customer_materials__material_id__patch"];
        trace?: never;
    };
    "/api/customer-materials/{material_id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Material Facts
         * @description List facts associated with a customer material.
         */
        get: operations["list_material_facts_api_customer_materials__material_id__facts_get"];
        put?: never;
        /**
         * Add Material Fact
         * @description Add a fact to a customer material.
         */
        post: operations["add_material_fact_api_customer_materials__material_id__facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customer-materials/{material_id}/mark-uploaded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Material Uploaded
         * @description Mark a customer material as uploaded.
         */
        post: operations["mark_material_uploaded_api_customer_materials__material_id__mark_uploaded_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Customers */
        get: operations["list_customers_api_customers_get"];
        put?: never;
        /** Create Customer */
        post: operations["create_customer_api_customers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer */
        get: operations["get_customer_api_customers__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Customer */
        patch: operations["update_customer_api_customers__customer_id__patch"];
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Board */
        get: operations["dashboard_board_api_dashboard_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard History */
        get: operations["dashboard_history_api_dashboard_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Plan */
        get: operations["dashboard_plan_api_dashboard_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Today */
        get: operations["dashboard_today_api_dashboard_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Facts */
        get: operations["list_facts_api_facts_get"];
        put?: never;
        /** Create Fact */
        post: operations["create_fact_api_facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facts/{fact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fact */
        get: operations["get_fact_api_facts__fact_id__get"];
        put?: never;
        post?: never;
        /** Delete Fact */
        delete: operations["delete_fact_api_facts__fact_id__delete"];
        options?: never;
        head?: never;
        /** Update Fact */
        patch: operations["update_fact_api_facts__fact_id__patch"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/facts/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Facts Overview */
        get: operations["get_facts_overview_api_knowledge_facts_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nightly-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nightly Review Placeholder */
        get: operations["nightly_review_placeholder_api_nightly_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Board Preferences */
        get: operations["get_board_preferences_api_preferences_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Board Preferences */
        patch: operations["update_board_preferences_api_preferences_board_patch"];
        trace?: never;
    };
    "/api/preferences/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Preferences */
        get: operations["get_knowledge_preferences_api_preferences_knowledge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Knowledge Preferences */
        patch: operations["update_knowledge_preferences_api_preferences_knowledge_patch"];
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects-v2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects V2 Compat */
        get: operations["list_projects_v2_compat_api_projects_v2_get"];
        put?: never;
        /** Create Project V2 Compat */
        post: operations["create_project_v2_compat_api_projects_v2_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects-v2/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project V2 Compat */
        get: operations["get_project_v2_compat_api_projects_v2__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Project V2 Compat */
        patch: operations["update_project_v2_compat_api_projects_v2__project_id__patch"];
        trace?: never;
    };
    "/api/projects/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Project Summaries
         * @description Lightweight project summaries with task counts (used by board hero).
         */
        get: operations["list_project_summaries_api_projects_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/review-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Review Batches */
        get: operations["list_review_batches_api_review_batches_get"];
        put?: never;
        /** Create Review Batch */
        post: operations["create_review_batch_api_review_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Batch */
        get: operations["get_review_batch_api_review_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Review Batch */
        patch: operations["update_review_batch_api_review_batches__batch_id__patch"];
        trace?: never;
    };
    "/api/review-batches/{batch_id}/customer-materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batch Materials */
        get: operations["list_batch_materials_api_review_batches__batch_id__customer_materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_api_tasks__task_id__patch"];
        trace?: never;
    };
    "/api/tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Task */
        post: operations["cancel_task_api_tasks__task_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Task */
        post: operations["complete_task_api_tasks__task_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/customer-materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Task Customer Materials
         * @description List materials linked to a task.
         *
         *     Uses raw SQL for the legacy task_id column (removed from ORM, still in DB
         *     until the alembic migration drops it).  This endpoint will be removed once
         *     the column is dropped.
         */
        get: operations["list_task_customer_materials_api_tasks__task_id__customer_materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/defer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Defer Task */
        post: operations["defer_task_api_tasks__task_id__defer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Reminder */
        post: operations["create_reminder_api_tasks__task_id__reminders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BoardPreferenceRead */
        BoardPreferenceRead: {
            /** Pinned Projects */
            pinned_projects?: string[];
            /** Project Order */
            project_order?: string[];
            /** Task Order */
            task_order?: number[];
        };
        /** BoardPreferenceUpdate */
        BoardPreferenceUpdate: {
            /** Pinned Projects */
            pinned_projects?: string[] | null;
            /** Project Order */
            project_order?: string[] | null;
            /** Task Order */
            task_order?: number[] | null;
        };
        /** BoardSummary */
        BoardSummary: {
            /** Groups */
            groups: components["schemas"]["TaskBoardGroup"][];
        };
        /** CustomerCreate */
        CustomerCreate: {
            /** Aliases */
            aliases?: string[];
            /** Area */
            area?: string | null;
            /** Description */
            description?: string | null;
            /** Key */
            key?: string | null;
            /** Name */
            name: string;
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "paused" | "closed";
            /** Tags */
            tags?: string[];
        };
        /** CustomerMaterialCreate */
        CustomerMaterialCreate: {
            /** Customer Id */
            customer_id?: number | null;
            /** Generation Meta */
            generation_meta?: {
                [key: string]: unknown;
            } | null;
            /** Material Date */
            material_date?: string | null;
            /**
             * Material Type
             * @default period_summary
             * @enum {string}
             */
            material_type: "period_summary" | "fact_bundle" | "meeting_note" | "project_digest";
            /** Period End */
            period_end?: string | null;
            /** Period Start */
            period_start?: string | null;
            /** Project V2 Id */
            project_v2_id?: number | null;
            /** Raw Facts Markdown */
            raw_facts_markdown?: string | null;
            /** Review Batch Id */
            review_batch_id?: number | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "approved" | "skipped" | "uploaded";
            /** Title */
            title: string;
        };
        /** CustomerMaterialFactCreate */
        CustomerMaterialFactCreate: {
            /** Fact Id */
            fact_id: number;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** CustomerMaterialFactRead */
        CustomerMaterialFactRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Fact Id */
            fact_id: number;
            /** Id */
            id: number;
            /** Material Id */
            material_id: number;
            /** Sort Order */
            sort_order: number;
        };
        /** CustomerMaterialRead */
        CustomerMaterialRead: {
            /** Archived At */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Id */
            customer_id?: number | null;
            /** Generation Meta */
            generation_meta?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: number;
            /** Material Date */
            material_date: string | null;
            /** Material Type */
            material_type?: string | null;
            /** Period End */
            period_end?: string | null;
            /** Period Start */
            period_start?: string | null;
            /** Project V2 Id */
            project_v2_id?: number | null;
            /** Raw Facts Markdown */
            raw_facts_markdown?: string | null;
            /** Review Batch Id */
            review_batch_id?: number | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CustomerMaterialUpdate */
        CustomerMaterialUpdate: {
            /**
             * Clear Batch
             * @default false
             */
            clear_batch: boolean;
            /**
             * Clear Project V2
             * @default false
             */
            clear_project_v2: boolean;
            /** Customer Id */
            customer_id?: number | null;
            /** Generation Meta */
            generation_meta?: {
                [key: string]: unknown;
            } | null;
            /** Material Date */
            material_date?: string | null;
            /** Material Type */
            material_type?: ("period_summary" | "fact_bundle" | "meeting_note" | "project_digest") | null;
            /** Period End */
            period_end?: string | null;
            /** Period Start */
            period_start?: string | null;
            /** Project V2 Id */
            project_v2_id?: number | null;
            /** Raw Facts Markdown */
            raw_facts_markdown?: string | null;
            /** Review Batch Id */
            review_batch_id?: number | null;
            /** Status */
            status?: ("pending" | "approved" | "skipped" | "uploaded") | null;
            /** Title */
            title?: string | null;
        };
        /** CustomerRead */
        CustomerRead: {
            /** Aliases */
            aliases: string[];
            /** Area */
            area: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Key */
            key: string | null;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Tags */
            tags: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CustomerUpdate */
        CustomerUpdate: {
            /** Aliases */
            aliases?: string[] | null;
            /** Area */
            area?: string | null;
            /** Description */
            description?: string | null;
            /** Key */
            key?: string | null;
            /** Name */
            name?: string | null;
            /** Status */
            status?: ("active" | "paused" | "closed") | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** DashboardPayload */
        DashboardPayload: {
            board: components["schemas"]["BoardSummary"];
            history: components["schemas"]["HistorySummary"];
            today: components["schemas"]["TodaySummary"];
        };
        /** FactCreate */
        FactCreate: {
            /** Customer Id */
            customer_id?: number | null;
            /**
             * Fact Date
             * Format: date-time
             */
            fact_date: string;
            /** Project Id */
            project_id?: number | null;
            /** Raw Markdown */
            raw_markdown: string;
            /**
             * Source Type
             * @default manual_input
             * @enum {string}
             */
            source_type: "chat" | "screenshot_ocr" | "task_completion" | "meeting_note" | "manual_input" | "forwarded_message" | "document";
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "draft" | "confirmed" | "rejected";
            /** Task Id */
            task_id?: number | null;
            /** Title */
            title: string;
            /** Value Types */
            value_types?: string[];
        };
        /** FactRead */
        FactRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Id */
            customer_id: number | null;
            /**
             * Fact Date
             * Format: date-time
             */
            fact_date: string;
            /** Id */
            id: number;
            /** Project Id */
            project_id: number | null;
            /** Raw Markdown */
            raw_markdown: string;
            /** Source Type */
            source_type: string;
            /** Status */
            status: string;
            /** Task Id */
            task_id: number | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Value Types */
            value_types: string[];
        };
        /** FactUpdate */
        FactUpdate: {
            /**
             * Clear Customer
             * @default false
             */
            clear_customer: boolean;
            /**
             * Clear Project
             * @default false
             */
            clear_project: boolean;
            /**
             * Clear Task
             * @default false
             */
            clear_task: boolean;
            /** Customer Id */
            customer_id?: number | null;
            /** Fact Date */
            fact_date?: string | null;
            /** Project Id */
            project_id?: number | null;
            /** Raw Markdown */
            raw_markdown?: string | null;
            /** Source Type */
            source_type?: ("chat" | "screenshot_ocr" | "task_completion" | "meeting_note" | "manual_input" | "forwarded_message" | "document") | null;
            /** Status */
            status?: ("draft" | "confirmed" | "rejected") | null;
            /** Task Id */
            task_id?: number | null;
            /** Title */
            title?: string | null;
            /** Value Types */
            value_types?: string[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Db */
            db: string;
            /**
             * Now
             * Format: date-time
             */
            now: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HistorySummary */
        HistorySummary: {
            /** Tasks */
            tasks: components["schemas"]["TaskRead"][];
            /** Total */
            total: number;
        };
        /** KnowledgeFactCustomerOverview */
        KnowledgeFactCustomerOverview: {
            /** Area */
            area: string | null;
            /** Customer Id */
            customer_id: number | null;
            /** Customer Name */
            customer_name: string;
            /** Fact Count */
            fact_count: number;
            /** Latest Fact At */
            latest_fact_at: string | null;
            /** Project Count */
            project_count: number;
            /** Projects */
            projects: components["schemas"]["KnowledgeFactProjectOverview"][];
        };
        /** KnowledgeFactProjectOverview */
        KnowledgeFactProjectOverview: {
            /** Fact Count */
            fact_count: number;
            /** Latest Fact At */
            latest_fact_at: string | null;
            /** Project Id */
            project_id: number | null;
            /** Project Name */
            project_name: string;
            /** Status */
            status: string | null;
        };
        /** KnowledgeFactsOverview */
        KnowledgeFactsOverview: {
            /** Customers */
            customers: components["schemas"]["KnowledgeFactCustomerOverview"][];
            /** Total Fact Count */
            total_fact_count: number;
        };
        /** KnowledgePreferenceRead */
        KnowledgePreferenceRead: {
            /** Customer Order Ids */
            customer_order_ids?: number[];
            /** Pinned Customer Ids */
            pinned_customer_ids?: number[];
        };
        /** KnowledgePreferenceUpdate */
        KnowledgePreferenceUpdate: {
            /** Customer Order Ids */
            customer_order_ids?: number[] | null;
            /** Pinned Customer Ids */
            pinned_customer_ids?: number[] | null;
        };
        /** NightlyReviewPlaceholder */
        NightlyReviewPlaceholder: {
            /**
             * Cutoff Hour
             * @default 22
             */
            cutoff_hour: number;
            /** Note */
            note: string;
            /** Pending Candidates */
            pending_candidates: number;
            /**
             * Supported
             * @default true
             */
            supported: boolean;
        };
        /** PlanGroup */
        PlanGroup: {
            /** Group Date */
            group_date?: string | null;
            /** Key */
            key: string;
            /** Tasks */
            tasks: components["schemas"]["TaskRead"][];
            /** Title */
            title: string;
        };
        /** PlanSummary */
        PlanSummary: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open Count */
            open_count: number;
            /** Plan Groups */
            plan_groups?: components["schemas"]["PlanGroup"][];
            /** Total */
            total: number;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Actual End At */
            actual_end_at?: string | null;
            /** Area */
            area?: string | null;
            /** Customer Id */
            customer_id?: number | null;
            /** Name */
            name: string;
            /**
             * Project Type
             * @default customer
             * @enum {string}
             */
            project_type: "customer" | "personal" | "internal";
            /** Start At */
            start_at?: string | null;
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "waiting" | "done" | "canceled";
            /** Tags */
            tags?: string[];
            /** Target End At */
            target_end_at?: string | null;
        };
        /** ProjectRead */
        ProjectRead: {
            /** Actual End At */
            actual_end_at: string | null;
            /** Area */
            area: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Id */
            customer_id: number | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Project Type */
            project_type: string;
            /** Start At */
            start_at: string | null;
            /** Status */
            status: string;
            /** Tags */
            tags: string[];
            /** Target End At */
            target_end_at: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Done Task Count */
            done_task_count: number;
            /** Name */
            name: string;
            /** Open Task Count */
            open_task_count: number;
            /** Task Count */
            task_count: number;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Actual End At */
            actual_end_at?: string | null;
            /** Area */
            area?: string | null;
            /**
             * Clear Customer
             * @default false
             */
            clear_customer: boolean;
            /** Customer Id */
            customer_id?: number | null;
            /** Name */
            name?: string | null;
            /** Project Type */
            project_type?: ("customer" | "personal" | "internal") | null;
            /** Start At */
            start_at?: string | null;
            /** Status */
            status?: ("active" | "waiting" | "done" | "canceled") | null;
            /** Tags */
            tags?: string[] | null;
            /** Target End At */
            target_end_at?: string | null;
        };
        /** ReminderCreate */
        ReminderCreate: {
            /**
             * Channel
             * @default local
             */
            channel: string;
            /** Note */
            note?: string | null;
            /**
             * Remind At
             * Format: date-time
             */
            remind_at: string;
        };
        /** ReminderRead */
        ReminderRead: {
            /** Channel */
            channel: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Note */
            note: string | null;
            /**
             * Remind At
             * Format: date-time
             */
            remind_at: string;
            /** Status */
            status: string;
            /** Task Id */
            task_id: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ReviewBatchCreate */
        ReviewBatchCreate: {
            /**
             * Batch Type
             * @default weekly_customer_summary
             * @enum {string}
             */
            batch_type: "weekly_customer_summary" | "daily_customer_summary" | "manual_generation";
            /**
             * Created By
             * @default manual
             */
            created_by: string;
            /**
             * Material Count
             * @default 0
             */
            material_count: number;
            /** Period End */
            period_end?: string | null;
            /** Period Start */
            period_start?: string | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "partial" | "approved" | "uploaded";
            /** Title */
            title: string;
        };
        /** ReviewBatchRead */
        ReviewBatchRead: {
            /** Batch Type */
            batch_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Id */
            id: number;
            /** Material Count */
            material_count: number;
            /** Period End */
            period_end: string | null;
            /** Period Start */
            period_start: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ReviewBatchUpdate */
        ReviewBatchUpdate: {
            /** Batch Type */
            batch_type?: ("weekly_customer_summary" | "daily_customer_summary" | "manual_generation") | null;
            /** Created By */
            created_by?: string | null;
            /** Material Count */
            material_count?: number | null;
            /** Period End */
            period_end?: string | null;
            /** Period Start */
            period_start?: string | null;
            /** Status */
            status?: ("pending" | "partial" | "approved" | "uploaded") | null;
            /** Title */
            title?: string | null;
        };
        /** TaskActionCancel */
        TaskActionCancel: {
            /** Canceled At */
            canceled_at?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** TaskActionComplete */
        TaskActionComplete: {
            /** Completed At */
            completed_at?: string | null;
            /** Note */
            note?: string | null;
        };
        /** TaskActionDefer */
        TaskActionDefer: {
            /**
             * Deferred To
             * Format: date-time
             */
            deferred_to: string;
            /** Due At */
            due_at?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** TaskBoardGroup */
        TaskBoardGroup: {
            /** Status */
            status: string;
            /** Tasks */
            tasks: components["schemas"]["TaskRead"][];
        };
        /** TaskCreate */
        TaskCreate: {
            /** Area */
            area?: string | null;
            /** Customer Id */
            customer_id?: number | null;
            /** Description */
            description?: string | null;
            /** Due At */
            due_at?: string | null;
            /** Project */
            project?: string | null;
            /** Project Id */
            project_id?: number | null;
            recurrence?: components["schemas"]["TaskRecurrenceWrite"] | null;
            /** Reminders */
            reminders?: components["schemas"]["ReminderCreate"][];
            /**
             * Source
             * @default web
             */
            source: string;
            /** Source Type */
            source_type?: string | null;
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
        };
        /** TaskDetail */
        TaskDetail: {
            /** Area */
            area: string | null;
            /** Canceled At */
            canceled_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Completion Note */
            completion_note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Id */
            customer_id: number | null;
            /** Deferred To */
            deferred_to: string | null;
            /** Description */
            description: string | null;
            /** Due At */
            due_at: string | null;
            /** Events */
            events?: components["schemas"]["TaskEventRead"][];
            /** Id */
            id: number;
            /** Nightly Bucket */
            nightly_bucket: string | null;
            /** Nightly Reviewed At */
            nightly_reviewed_at: string | null;
            /** Project */
            project: string | null;
            /** Project Id */
            project_id: number | null;
            recurrence?: components["schemas"]["TaskRecurrenceRead"] | null;
            /** Reminders */
            reminders?: components["schemas"]["ReminderRead"][];
            /** Source */
            source: string;
            /** Source Type */
            source_type?: string | null;
            /** Status */
            status: string;
            /** Tags */
            tags: string[];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TaskEventRead */
        TaskEventRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Event Type */
            event_type: string;
            /** Id */
            id: number;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Task Id */
            task_id: number;
        };
        /** TaskRead */
        TaskRead: {
            /** Area */
            area: string | null;
            /** Canceled At */
            canceled_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Completion Note */
            completion_note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Id */
            customer_id: number | null;
            /** Deferred To */
            deferred_to: string | null;
            /** Description */
            description: string | null;
            /** Due At */
            due_at: string | null;
            /** Id */
            id: number;
            /** Nightly Bucket */
            nightly_bucket: string | null;
            /** Nightly Reviewed At */
            nightly_reviewed_at: string | null;
            /** Project */
            project: string | null;
            /** Project Id */
            project_id: number | null;
            recurrence?: components["schemas"]["TaskRecurrenceRead"] | null;
            /** Reminders */
            reminders?: components["schemas"]["ReminderRead"][];
            /** Source */
            source: string;
            /** Source Type */
            source_type?: string | null;
            /** Status */
            status: string;
            /** Tags */
            tags: string[];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TaskRecurrenceRead */
        TaskRecurrenceRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Day Of Month */
            day_of_month?: number | null;
            /**
             * Days Of Week
             * @description ISO weekday numbers: 1=Mon ... 7=Sun
             */
            days_of_week?: number[];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** End At */
            end_at?: string | null;
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "daily" | "weekly" | "monthly";
            /** Id */
            id: number;
            /**
             * Interval
             * @default 1
             */
            interval: number;
            /** Last Run At */
            last_run_at: string | null;
            /** Next Run At */
            next_run_at: string | null;
            /**
             * Reminder Offsets Minutes
             * @description Minutes before due time, e.g. [30, 1440]
             */
            reminder_offsets_minutes?: number[];
            /** Start At */
            start_at?: string | null;
            /** Task Id */
            task_id: number;
            /**
             * Time Of Day
             * @description HH:MM or HH:MM:SS
             */
            time_of_day?: string | null;
            /**
             * Timezone
             * @default Asia/Shanghai
             */
            timezone: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TaskRecurrenceWrite */
        TaskRecurrenceWrite: {
            /** Day Of Month */
            day_of_month?: number | null;
            /**
             * Days Of Week
             * @description ISO weekday numbers: 1=Mon ... 7=Sun
             */
            days_of_week?: number[];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** End At */
            end_at?: string | null;
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "daily" | "weekly" | "monthly";
            /**
             * Interval
             * @default 1
             */
            interval: number;
            /**
             * Reminder Offsets Minutes
             * @description Minutes before due time, e.g. [30, 1440]
             */
            reminder_offsets_minutes?: number[];
            /** Start At */
            start_at?: string | null;
            /**
             * Time Of Day
             * @description HH:MM or HH:MM:SS
             */
            time_of_day?: string | null;
            /**
             * Timezone
             * @default Asia/Shanghai
             */
            timezone: string;
        };
        /** TaskUpdate */
        TaskUpdate: {
            /** Area */
            area?: string | null;
            /**
             * Clear Customer
             * @default false
             */
            clear_customer: boolean;
            /**
             * Clear Project V2
             * @default false
             */
            clear_project_v2: boolean;
            /**
             * Clear Recurrence
             * @default false
             */
            clear_recurrence: boolean;
            /** Customer Id */
            customer_id?: number | null;
            /** Description */
            description?: string | null;
            /** Due At */
            due_at?: string | null;
            /** Project */
            project?: string | null;
            /** Project Id */
            project_id?: number | null;
            recurrence?: components["schemas"]["TaskRecurrenceWrite"] | null;
            /** Source */
            source?: string | null;
            /** Source Type */
            source_type?: string | null;
            /** Status */
            status?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Title */
            title?: string | null;
        };
        /** TodaySummary */
        TodaySummary: {
            /** Completed Count */
            completed_count: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open Count */
            open_count: number;
            /** Plan Groups */
            plan_groups?: components["schemas"]["PlanGroup"][];
            /** Tasks */
            tasks: components["schemas"]["TaskRead"][];
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_customer_materials_api_customer_materials_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: string | null;
                include_archived?: boolean;
                limit?: number;
                customer_id?: number | null;
                project_v2_id?: number | null;
                review_batch_id?: number | null;
                material_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMaterialRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_customer_material_api_customer_materials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerMaterialCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMaterialRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_material_api_customer_materials__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMaterialRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_customer_material_api_customer_materials__material_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMaterialRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_customer_material_api_customer_materials__material_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerMaterialUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMaterialRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_material_facts_api_customer_materials__material_id__facts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMaterialFactRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_material_fact_api_customer_materials__material_id__facts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerMaterialFactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMaterialFactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_material_uploaded_api_customer_materials__material_id__mark_uploaded_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMaterialRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_customers_api_customers_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_customer_api_customers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_api_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_customer_api_customers__customer_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardPayload"];
                };
            };
        };
    };
    dashboard_board_api_dashboard_board_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardSummary"];
                };
            };
        };
    };
    dashboard_history_api_dashboard_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistorySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_plan_api_dashboard_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"];
                };
            };
        };
    };
    dashboard_today_api_dashboard_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodaySummary"];
                };
            };
        };
    };
    list_facts_api_facts_get: {
        parameters: {
            query?: {
                customer_id?: number | null;
                project_id?: number | null;
                project_unassigned?: boolean;
                task_id?: number | null;
                status?: string | null;
                source_type?: string | null;
                from?: string | null;
                to?: string | null;
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_fact_api_facts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fact_api_facts__fact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_fact_api_facts__fact_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_fact_api_facts__fact_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    history_api_history_get: {
        parameters: {
            query?: {
                date?: string | null;
                status?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistorySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_facts_overview_api_knowledge_facts_overview_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeFactsOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nightly_review_placeholder_api_nightly_review_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NightlyReviewPlaceholder"];
                };
            };
        };
    };
    get_board_preferences_api_preferences_board_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardPreferenceRead"];
                };
            };
        };
    };
    update_board_preferences_api_preferences_board_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardPreferenceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardPreferenceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_preferences_api_preferences_knowledge_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgePreferenceRead"];
                };
            };
        };
    };
    update_knowledge_preferences_api_preferences_knowledge_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgePreferenceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgePreferenceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: {
                customer_id?: number | null;
                area?: string | null;
                status?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_v2_compat_api_projects_v2_get: {
        parameters: {
            query?: {
                customer_id?: number | null;
                area?: string | null;
                status?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_v2_compat_api_projects_v2_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_v2_compat_api_projects_v2__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_v2_compat_api_projects_v2__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_summaries_api_projects_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_review_batches_api_review_batches_get: {
        parameters: {
            query?: {
                batch_type?: string | null;
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_batch_api_review_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewBatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_batch_api_review_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_review_batch_api_review_batches__batch_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewBatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batch_materials_api_review_batches__batch_id__customer_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMaterialRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                status?: string | null;
                date?: string | null;
                q?: string | null;
                source_type?: string | null;
                from?: string | null;
                to?: string | null;
                customer_id?: number | null;
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_task_api_tasks__task_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskActionCancel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_task_api_tasks__task_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskActionComplete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_task_customer_materials_api_tasks__task_id__customer_materials_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMaterialRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    defer_task_api_tasks__task_id__defer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskActionDefer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_reminder_api_tasks__task_id__reminders_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
